php_xdebug_package: php-xdebug

php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-curl
  - php7.0-intl
  - php7.0-gd
  - php7.0-sqlite3
  - php7.0-dev
  - libmagickwand-6.q16-dev
  - pkg-config

php_mysql_package: php7.0-mysql
  
php_pgsql_package: php7.0-pgsql


#/etc/php5 auf debian
etc_php_path: /etc/php/7.0/

#php5enmod auf debian
phpenmod: phpenmod
